"use strict";
exports.__esModule = true;
var Imdb_1 = require("./Imdb");
var movie_1 = require("./movie");
var fs = require('fs');
var movie1 = new movie_1.Movie("Intocable", 2014, "France", "Dranma");
var movie2 = new movie_1.Movie("Intocable", 2014, "France", "Dranma");
var movie3 = new movie_1.Movie("Intocable", 2014, "France", "Dranma");
var movie4 = new movie_1.Movie("Intocable", 2014, "France", "Dranma");
var imdb1 = new Imdb_1.Imdb([movie1, movie2, movie3, movie3]);
console.log(JSON.stringify(imdb1));
var objson = JSON.stringify(imdb1);
fs.writeFileSync("imdbBBDD.json", objson);
